{% set name = "botocore-stubs" %}
{% set version = "1.29.146" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 183abbfbd5e98a370f6041277200f285cd274dd8316f6a53504686b6795778b1

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.6
  run:
    - python >=3.6
    - types-awscrt
    - typing_extensions

test:
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/vemel/mypy_boto3_builder
  summary: Type annotations for botocore.
  dev_url: https://github.com/vemel/mypy_boto3_builder/tree/main/types_botocore
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
