{% set name = "botocore-stubs" %}
{% set version = "1.35.60" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: ae2b94b099d43204db6d056b763fff47ebc5974fab24420e7f4a01526a590048

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - setuptools
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - types-awscrt
    - typing_extensions >=4.1.0

test:
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/vemel/mypy_boto3_builder
  summary: Type annotations for botocore.
  dev_url: https://github.com/vemel/mypy_boto3_builder/tree/main/types_botocore
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
