{% set name = "botocore-stubs" %}
{% set version = "1.31.45" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 9036f753cfce92111206401a7e73874576fcd8f6690e9c161a4ce5ccce9da8f2

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.7,<4.0
  run:
    - python >=3.7,<4.0
    - types-awscrt
    - typing_extensions >=4.1.0

test:
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/vemel/mypy_boto3_builder
  summary: Type annotations for botocore.
  dev_url: https://github.com/vemel/mypy_boto3_builder/tree/main/types_botocore
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
