{% set name = "botocore-stubs" %}
{% set version = "1.34.65" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 7c510adb2c6ffee2e2a5f198c1030bb8edff2136ee56e46729c02ea37b2424a5

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.8,<4.0
  run:
    - python >=3.8,<4.0
    - types-awscrt
    - typing_extensions >=4.1.0

test:
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/vemel/mypy_boto3_builder
  summary: Type annotations for botocore.
  dev_url: https://github.com/vemel/mypy_boto3_builder/tree/main/types_botocore
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
