schema_version: 1

context:
  name: botocore-stubs
  version: "1.40.75"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: 2e893e1c265c4af6da369d8918c9957ae63875b8735cd45ebc824d5fedd6afd5

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - setuptools
    - python ${{ python_min }}.*
  run:
    - python >=${{ python_min }}
    - types-awscrt
    - typing_extensions >=4.1.0

tests:
  - requirements:
      run:
        - pip
        - python ${{ python_min }}
    script:
      - python -c "import importlib; importlib.import_module('botocore-stubs')"
      - pip check

about:
  summary: Type annotations for botocore.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/vemel/mypy_boto3_builder
  repository: https://github.com/vemel/mypy_boto3_builder/tree/main/types_botocore

extra:
  recipe-maintainers:
    - thewchan
